import { cn } from "@nextui-org/theme"
import type { Metadata } from "next"

import { fontSans } from "@/app/fonts"
import { Providers } from "@/app/providers"
import "@/app/styles/index.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"overflow-x-hidden overflow-y-scroll font-sans antialiased",
					fontSans.variable,
				)}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
